language: cpp

sudo: false

os:
  - linux

compiler:
  - clang
  - gcc

before_install: if [ "$CXX" = "g++" ]; then export CXX=g++-7; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-7-dev
      - g++-7
      - libncursesw5-dev
  coverity_scan:
    project:
      name: "CharlesGueunet/kakoune"
      description: "Build submitted via Travis CI"
    notification_email: charles.gueunet@kitware.com
    build_command_prepend: "cd build && make clean"
    build_command: "ctest -D Experimental"
    branch_pattern: coverity-scan

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - ctest -D Experimental
